name: re_open_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  crypto: ^3.0.3
  custom_platform_device_id: ^1.0.8
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_gen_runner: ^5.4.0
  flutter_staggered_grid_view: ^0.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^14.1.2
  image_picker: ^1.1.1
  json_annotation: ^4.9.0
  just_audio: ^0.9.38
  path_provider: ^2.1.3
  record: ^5.1.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  talker_dio_logger: ^4.2.0
  talker_flutter: ^4.2.0
  unicons: ^2.1.1
  vibration: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/